### ISSUE TITLE
Suggestion: Add "Notification" theming support

### ISSUE THREAD

**Issue by someone5678** [suchmememanyskill/SDH-CssLoader#55]
Steam separates notification components into "notificationtoasts".
So we can't theming it until we add mapping.

In `css_tab_mapping.py`
```PYTHON
def load_tab_mappings():
    global TAB_MAPPINGS_INTERNAL
    TAB_MAPPINGS_INTERNAL = {
        "QuickAccess": ["QuickAccess", "QuickAccess_.*"],
        "MainMenu": ["MainMenu", "MainMenu_.*"],
        "All": ["SP", "QuickAccess", "QuickAccess_.*", "MainMenu", "MainMenu_.*", "Steam Big Picture Mode"],
        "SP": ["SP", "Steam Big Picture Mode"],
        "Notification": [ "notificationtoasts", "notificationtoasts_.*"]
    }
```

In `css_theme.py`
```PYTHON
            self.injects = [Inject(os.path.join(themePath, "theme.css"), ["SP", "QuickAccess", "MainMenu", "Notification"], self)]
```

This change makes us enable to theming notifications.

Test:

In shared.css
```CSS
/* Notification */
.notificationcontent_ShortTemplate_2w-Eq, .notificationcontent_PinnedTemplate_H_NPi, .notificationcontent_StandardTemplate_1B_uv, .notificationcontent_ShortTemplate_nwer8, .notificationcontent_StandardTemplate_5HZT7, .notificationcontent_PinnedTemplateDesktop_1-8YO, .notificationcontent_PinnedTemplate_1X-O1 {
  background: #222209 !important;
}

```

![20230125013308_1](https://user-images.githubusercontent.com/59456192/214352723-c871889f-b008-4f6b-87f9-7cfe020efe82.jpg)
